### PR TITLE
Update Input_Validation_Cheat_Sheet.md

### PR DESCRIPTION
**Pull request by aayush420**
Few typo fixes

### CODE REVIEW

**Comment by aayush420** [comment]
Addresses issue #60 from OWASP main repo. https://github.com/OWASP/owasp.github.io/issues/60

**Comment by ThunderSon** [comment]
@aayush420 Can I bother you to replicate this on the [official repository for the cheatsheets](https://github.com/OWASP/CheatSheetSeries/). The cheatsheets are being removed from this repository to be able to maintain them without bearing a huge maintenance cost.

**Comment by aayush420** [comment]
Sure

**Comment by aayush420** [comment]
#371 from the new repo https://github.com/OWASP/CheatSheetSeries/pull/371

**Pull request closed without merging**
